config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root 'jokes#index'
  resources :jokes, only: %i[index edit create update destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/joke.rb
# frozen_string_literal: true

class Joke < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/jokes_controller.rb
# frozen_string_literal: true

class JokesController < ApplicationController
  before_action :set_region
  before_action :set_joke, only: %i[edit update destroy]

  # GET /jokes or /jokes.json
  def index
    @joke = Joke.new
    @jokes = Joke.all.order(created_at: :desc)
  end

  # GET /jokes/new
  def new
    @joke = Joke.new
  end

  # GET /jokes/1/edit
  def edit; end

  # POST /jokes or /jokes.json
  def create
    @joke = Joke.new(joke_params)

    respond_to do |format|
      if @joke.save
        format.html { redirect_to jokes_path, flash: { notice: '成功建立笑話' } }
      else
        @jokes = Joke.all.order(created_at: :desc)
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jokes/1 or /jokes/1.json
  def update
    respond_to do |format|
      if @joke.update(joke_params)
        format.html { redirect_to jokes_path, flash: { notice: '成功更新笑話' } }
        format.json { render :show, status: :ok, location: @joke }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @joke.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jokes/1 or /jokes/1.json
  def destroy
    @joke.destroy
    respond_to do |format|
      format.html { redirect_to jokes_path, flash: { notice: '成功刪除笑話' } }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_joke
    @joke = Joke.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def joke_params
    params.require(:joke).permit(:title, :content)
  end

  def set_region
    @region = case ENV['REGION']
              when 'US' then '🇺🇸'
              when 'TW' then '🇹🇼'
              when 'Staging' then '🚀'
              else
                '🛠'
              end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/jokes_helper.rb
# frozen_string_literal: true

module JokesHelper
end

app/views/jokes/_form.html.erb
<%= form_with(model: joke) do |form| %>
  <% if joke.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(joke.errors.count, "error") %> prohibited this joke from being saved:</h2>

      <ul>
        <% joke.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label '標題', class: 'label' %>
    <%= form.text_field :title, class: 'input' %>
  </div>

  <div class="field">
    <%= form.label '內容', class: 'label' %>
    <%= form.text_area :content, class: 'textarea' %>
  </div>

  <div class="buttons">
    <% if @joke.persisted? %>
      <%= link_to '取消', jokes_path, class: 'button is-light' %>
      <%= form.submit '更新', class: 'button is-success is-light' %>
    <% else %>
      <%= form.submit '建立', class: 'button is-success is-light' %>
    <% end %>
  </div>
<% end %>

app/views/jokes/edit.html.erb
<div class="container">
  <h1 class="title is-1 mt-6 block">編輯</h1>
  <table class="table is-bordered mb-3 is-fullwidth">
    <tbody>
      <tr>
        <td colspan="2">
          <%= render 'form', joke: @joke %>
        </td>
      </tr>
    </tbody>
  </table>
</div>

app/views/jokes/index.html.erb
<div class="container">
  <% if notice.present? %>
    <article class="message is-success">
      <div class="message-body">
        <%= notice %>
      </div>
    </article>
  <% end %>
  <h1 class="title is-1 mt-6 block">🤣 笑話集 <%= @region %></h1>
  <table class="table is-bordered mb-3 is-fullwidth">
    <tbody>
      <tr>
        <td colspan="2">
          <%= render 'form', joke: @joke %>
        </td>
      </tr>
      <% @jokes.each do |joke| %>
        <tr>
          <td class="p-5">
            <div class="block is-size-4"><%= joke.title %></div>
            <div class="block is-size-5">
              <pre class="has-background-white pl-0"><%= joke.content %></pre>
            </div>
          </td>
          <td>
            <div class="buttons">
              <%= link_to '編輯', edit_joke_path(joke), class: 'button is-info is-light' %>
              <%= link_to '刪除', joke, method: :delete, data: { confirm: '確定要刪除嗎？' }, class: 'button is-danger is-light' %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>